name: generate random grid animation

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install svgwrite

      - name: Generate random grid
        run: |
          python generate_random_grid.py

      - name: Generate SVG from random grid
        run: |
          python create_svg_from_grid.py
          mv dist/random_grid.svg dist/github-contribution-grid-snake.svg
          mv dist/random_grid_dark.svg dist/github-contribution-grid-snake-dark.svg

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
