name: Generate Random Grid Animation

on:
  schedule:
    - cron: "0 2 * * *" # Chạy lúc 2 AM hàng ngày
  workflow_dispatch: # Cho phép kích hoạt thủ công
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Phiên bản mới

      - name: Set up Python
        uses: actions/setup-python@v5 # Phiên bản mới
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install svgwrite

      - name: Generate random grid data
        run: python generate_random_grid.py

      - name: Create SVG from grid data
        run: python create_svg_from_grid.py

      - name: Push SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
